server:
    port: 8080

spring:

    application:
        name: hotelreservation

    jpa:
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:postgresql://localhost:5432/hotel-reservation
        username: postgres
        password: ${DB_PASSWORD}
